document:
  name: eIDAS Italian Wallet Technical Specifications
  description: |
    eIDAS Italian Wallet Technical Specifications
  tags:
    - standard 
    - interoperabilità
    - spid
    - cie
    - openid
  
